name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clj-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: clj-tests
      uses: vouch-opensource/tools.deps-build@1.0.1
      with:
        alias: :test:runner
  cljs-test:
    runs-on: ubuntu-latest
    steps:
    - name: install graal
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.1.java11'
    - name: install clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - name: install node
      uses: thonatos/github-actions-nodejs@v0.1.1
    - name: cljs-tests
      run: npx shadow-cljs compile :test 
